using System;
using CrossSync.Entity.Abstractions;

namespace CrossSync.Entity
{
  /// <summary>
  /// Versionable entity server side interface
  /// </summary>
  public interface IVersionableEntity : IIdentifiable
  {
    /// <summary>
    /// Gets the entity version.
    /// </summary>
    /// <remarks>Auto generated by SQL Server</remarks>
    byte[] Version { get; set; }

    /// <summary>
    /// Entity updated date used to filter entities which have to be requested by clients
    /// </summary>
    DateTimeOffset UpdatedAt { get; set; }
  }
}
